# Generated by Django 5.2.7 on 2025-11-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='page',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='page',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
